### ISSUE TITLE
U8 fields bug

### ISSUE THREAD

**Issue by psylity** [AndrewSpittlemeister/bytechomp#2] opened 2023-08-17 17:23 UTC
I experience an ugly issue :(

following code
```python
from dataclasses import dataclass
from bytechomp import Reader
from bytechomp.datatypes import U8, U32


@dataclass
class TestClass:
    F0: U32
    F1: U8
    F2: U32
    F3: U32


input_data = b"\x00\x00\x00\x00\xAA\xBB\xBB\xBB\xBB\xCC\xCC\xCC\xCC\x00\x00\x00"  # had to add \x00 * 3 to trigger reader.is_complete()


def hexdump(data: bytes):
    return "".join("%02x " % b for b in data)


reader = Reader[TestClass]().allocate()
reader.feed(input_data)
if reader.is_complete():
    response = reader.build()
    print("input data: ", hexdump(input_data))
    print("F0: %08X" % response.F0)
    print("F1: %08X" % response.F1)
    print("F2: %08X" % response.F2)
    print("F3: %08X" % response.F3)
```

returns:
```
input data:  00 00 00 00 aa bb bb bb bb cc cc cc cc 00 00 00 
F0: 00000000
F1: 000000AA
F2: CCCCCCBB
F3: 000000CC
```

expected behavior:
```
input data:  00 00 00 00 aa bb bb bb bb cc cc cc cc 00 00 00 
F0: 00000000
F1: 000000AA
F2: BBBBBBBB
F3: CCCCCCCC
```

**Comment by bmarroquin** [comment] 2023-09-12 06:58
It looks like the issue is with adding the native `@` prefix. Changing `@` to `=` creates the expected behavior. The native size adds padding bytes.
I'll submit a PR to add the Byte Order `NATIVE_STANDARD` and it will work as expected. I think this should be the default as it will be ~~more reliable.~~ more intuitive.

**Comment by AndrewSpittlemeister** [comment] 2023-10-04 13:41
@bmarroquin, merged in your pull request, thanks for giving some life to this project lol. Hopefully in the future I'll be able to do work on projects like this.

**Closed as completed by AndrewSpittlemeister** 2023-10-04 13:41 UTC
